export default{
    path:'/movie',
    component:()=>import('@/views/Movie'),
    children:[
        {
            path:'City',
            component:()=>import('@/components/City')
        },
        {
            path:'NowPlaying',
            component:()=>import('@/components/NowPlaying')
        },
        {
            path:'ComingSoon',
            component:()=>import('@/components/ComingSoon')
        },
        {
            path:'Search',
            component:()=>import('@/components/Search')
        },        
        {
            path:'detail/1/:movieId',
            components:{
                default:()=>import('@/components/NowPlaying'),
                detail:() =>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },
        {
            path:'detail/2/:movieId',
            components:{
                default:()=>import('@/components/ComingSoon'),
                detail:() =>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },
        {
            path:'/movie',
            redirect:'/movie/nowPlaying'
        }
    ]
}